# Generated by Django 6.0.3 on 2026-05-04 04:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-create']},
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item1', 'To Do'), ('item2', 'In Progress'), ('item3', 'Complete')], default='To Do', max_length=200),
            preserve_default=False,
        ),
    ]
