# Generated by Django 6.0.3 on 2026-05-04 04:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_options_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], max_length=200),
        ),
    ]
